/*
 * This Spock specification was generated by the Gradle 'init' task.
 */

import implementations.APISpecBuilder
import implementations.StatusSpecBuilder
import interfaces.StatusSpec
import spock.lang.Specification

import java.util.function.Predicate

class MainTest extends Specification {

    def "baseUrl validation works"() {
        def API = new APISpecBuilder()

        when:
        Boolean resultNotValid = API.validateUrl("localhosttest")
        Boolean resultValid = API.validateUrl("https://www.test.com/api")

        then:
        !resultNotValid
        resultValid
    }

    def "status builder works for body"() {
        def newStatusBuilder1 = new StatusSpecBuilder()

        when:
        StatusSpec newStatus = newStatusBuilder1.setLabel("statusLabel").setBody("statusBody").build()

        then:
        newStatus.getBody().equals("statusBody")
        newStatus.getLabel().equals("statusLabel")


    }



}
