/*
 * This Spock specification was generated by the Gradle 'init' task.
 */

import implementations.APISpecBuilder
import spock.lang.Specification

class MainTest extends Specification {

    def "baseUrl validation works"() {
        def API = new APISpecBuilder()

        when:
        Boolean resultNotValid = API.validateUrl("localhosttest")
        Boolean resultValid = API.validateUrl("https://www.test.com/api")

        then:
        !resultNotValid
        resultValid
    }


}
